spring.application.name=user-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/user_api?sslmode=disable
spring.datasource.username=user_api
spring.datasource.password=user_api_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true